-- Generated by scripts/generate-policy-lua from support-snapshot.json.
-- Do not edit by hand; regenerate when the snapshot changes.
return {
    maintained = {
        "8.2",
        "8.3",
        "8.4",
        "8.5",
    },
}
